### ISSUE TITLE
Applied Llamagistics has a hard dependency on Redstone Flux

### ISSUE THREAD

**Issue by Suiadan** [thiakil/Applied-Energistics-2#41]
Applied Llamagistics relies upon 'Redstone Flux' without having it as a dependency on curse so it auto-downloads... Tested in a small sp instance with only redstone flux and applied llamagistics. 

https://minecraft.curseforge.com/projects/redstone-flux

With only Forge, Applied Llamagistics, and Redstone Flux, the game launches fine. When I disable redstone flux, I get this error message:

(Full log: https://pastebin.com/2yASWRrX )

Description: There was a severe problem during mod loading that has caused the game to fail
 
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Llamagistics (appliedenergistics2)
Caused by: java.lang.IllegalAccessError: no such constructor: appeng.block.misc.BlockInscriber.<init>()void/newInvokeSpecial
    at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:448)
    at appeng.core.api.definitions.ApiBlocks.<init>(ApiBlocks.java:281)
    at appeng.core.ApiDefinitions.<init>(ApiDefinitions.java:45)
    at appeng.core.Api.<init>(Api.java:55)
    at appeng.core.Api.<clinit>(Api.java:41)
    at appeng.core.Registration.preInitialize(Registration.java:150)
    at appeng.core.AppEng.preInit(AppEng.java:168)

If there's anything else I can add, let me know...

- Minecraft Version: 1.12
- AE2 Version: applied-llamagistics-1.12-rv5-beta-3
- Forge Version: 14.21.1.2428

**Comment by thiakil** [comment]
Looks like a couple of interface names got missed in the annotation - it shouldn't be a hard dep
